### ISSUE TITLE
Homeworld - New/Repositioned Portals Don't Work

### ISSUE THREAD

**Issue by unaffected95** [jorn86/factorio-mods#1]
When a new portal is placed or the original one is removed and placed somewhere new they seen to no longer send any of their stockpiled resources. The Stockpile Reader doesn't recognize that there are any materials in them either.

I know farms and fisheries rely on certain positioning to work properly. Is there something similar with the portals themselves and I've just place them improperly or is there something actually wrong?

**Comment by jorn86** [comment]
I've been working on 0.1.0 for a while, which has a complete overhaul of how the entities, including portals are registered. It should fix all issues like this one. I was planning to release it soon anyway, so I might as well do it now.
